---
title: Zeitschichten
---
„Das römische Kastell „Confluentes“ an der Mündung der Mosel in den Rhein, zu Anfang des 4. Jahrhunderts errichtet, fiel nach mehreren Jahrhunderten der Reichsunmittelbarkeit im Jahr 1018 an den Trierer Erzbischof. [...] Koblenz überflügelte Trier und schwang sich zur Residenzstadt empor, was in der Anlage der Neustadt und im Bau des Schlosses (1786) durch den letzten Kurfürsten Clemens Wenzeslaus seinen sinnfälligen Ausdruck fand." [(Quelle: Stadtgeschichte, Stadt Koblenz)](https://www.koblenz.de/leben-in-koblenz/kultur/stadtportraet/stadtgeschichte/) 

## Die Zeit der französischen Herrschaft
Nach der Besetzung der Stadt durch französische Revolutionstruppen und der Flucht des letzten Kurfürsten Clemens Wenzeslaus inklusive eines Großteils seiner Beamten im Oktober 1794, gehörte Koblenz ab 1801 zu Frankreich und war zur Hauptstadt des Rhein-Mosel-Departements ernannt worden.
Unmittelbar nach der Besetzung von Koblenz bildeten die Franzosen eine Kommission aus Mitgliedern des Stadtrats, die in kurzer Zeit ein vollständiges Verzeichnis aller Häuser und ihrer Bewohner erstellte, wodurch die Planung und Durchführung der Unterbringung von Soldaten auf verfügbare Unterkünfte ermöglicht wurde. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 27.)

Die Zeit der französischen Herrschaft in Koblenz brachte u.a. eine Neuordnung der Verwaltung mit sich. Zu dieser gehörte die Umgestaltung der Zoll-, Steuer- und Finanzverwaltung, der diversen Güterverwaltungen, des Post- und Justizwesens, der Polizei, der Schul- und Kirchenorganisationen. In allen diesen Bereuchen wurde seit 1798 schrittweise die französische Gesetzgebung eingeführt. Dies bedeutete, dass neue Institutionen geschaffen, neues Personal rekrutiert und neue Verfahrensregeln eingeführt werden mussten. Der Bruch mit dem Althergebrachten war gravierend, und die Einführung der neuen Staats- und Gesellschaftsordnung verlief alles andere als reibungslos. Vor allem an den Stellen nicht, an denen die Eingriffe die traditionellen Lebensweisen und herkömmlichen sozialen Ordnungsmuster betraf. So zum Beispiel bei der Einführung der allgemeinen Rechtsgleichheit. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 33.)

Der politische Neuanfang ging für Koblenz mit einem deutlichen Bevölkerungswachstum einher und war mit erheblichen gesellschaftlichen Umschichtungen verbunden. Während die Bevölkerungszahl 1798 nur bei 7309 lag, stieg sie in den Folgejahren rasch auf 10.190 Personen an. Der Anstieg beruhte zum einen auf einem Geburtenüberschuss und zum anderen auf starke Zuwanderungsbewegungen. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 37.)

Die französische Zeit bewirkte in Koblenz nachhaltige Veränderungen im Denken und Handeln der Menschen. Unübersehbar war die Tendenz zur Verbürgerlichung des politischen, wirtschaftlichen und kulturellen Lebens. Es waren nicht mehr wie in residenzstädtischer Zeit der kurfürstliche Hof, der Adel und der Klerus, die die Maßstäbe setzten, sondern die bürgerliche Schicht aus Beamten, Kaufleuten und Unternehmern. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 45.)

## Die Zeit der preußischen Herrschaft

Mit dem Wiener Kongress wurde Koblenz 1815 Teil der preußischen Monarchie. Die preußische Regierung bestimmte die Stadt zur Verwaltungshauptstadt der preußischen Rheinlande und baute sie unter Einbeziehung der umliegenden Höhenzüge und des Ehrenbreitsteins zu einer Festungs aus. So entwicklete sich Koblenz bis in die 1890er Jahre zu einer Militär- und Beamtenstadt. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 49.)

Während die Stadt einerseits als hochgerüstete Militärfestung und als Verwaltungszentrum den spätabsolutistischen Obrigkeitsstaat symbolisierte, entwickelte sie sich im Vormärz andererseits zur rheinischen Hochburg eines nach Rom orientierten Katholizismus. Grundlegende Spannungen zwischen preußischem Staat und Zivilgemeinde, zwischen rheinischem Katholizismus, Liberalismus und protestantischem Zentralstaat sowie zwischen Stadtbürgertum und proletarisch-demokratischen Partizipationsbewegungen prägten mehr als hundert Jahre lang die Geschichte der Stadt. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 50.)

Die zahlreichen militärischen Institutionen und Soldaten beanspruchten auch im Stadtinnern viel Platz und eine große Zahl von Gebäuden. Von Anfang an mussten also in Koblenz die städtischen Interessen den militärischen weichen, wodurch das wirtschaftliche Gedeihen der Stadt entscheidend behindert wurde. Insbesondere beim Ankauf und der Beschlagnahme von großen Teilen des Stadtgebietes für de Festungsbau blieben Schwierigkeiten und Konflikte nicht aus. Einige Anwohner der Zollstraße waren zwar 1823 damit einverstanden, dass ihre Häuser fpr einen weiteren Mauerabschnitt am Rhein abgerissen werden mussten, forderten aber – statt einer finanziellen Entschädigung – dass die Regierung ihnen an geeigneter Stelle andere Häuser erbauen lasse. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 53.)

Fabriken, die mit dampfgetriebenen Maschinen und größeren Belegschaften produzierten, fehlten in der Stadt. Allein einige Tabakfabriken und die Blechlackfabrik con Hermann Josef Dietz sowie von Ferdinand und dessen Sohn Hubert Schaafhausen beschäftigten eine größere Zahl von Arbeitern. In den 1830er Jahren arbeiteten 70 und seit den 1840er Jahren 120 bis 150 Männer in der inzwischen erweiterten Blechwaren-, Steinpappe- und Lackierfabrik, die seit 1806 in der "Alten Burg" untergebracht war. Handwerkliche Produktion für den lokalen Markt und Kleinbetriebe bestimmten das Bild. Verwaltung, Garnison und Fremdenverkehr erforderten zugleich zahlreiche Hilfs- und gesindearbeiten und ließen eine große Nachfrage nach vielfältigen Dienstleistungen, Wohnungen und Gastwirtschaften entstehen. Die überlieferten preußischen Gewerbestatistiken von 1816/17 und 1849 zeigen, dass in der ersten Hälfte des 19. Jahrhunderts in Koblenz noch fast die Hälfte der Erwerbstätigen selbstständige Gewerbe- oder Handeltreibende, Beamte oder Rentner waren. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 59.)

Institutionen wie Zünfte und Klöster, die traditionell Sicherheit gewähren oder die Armen und Kranken versorgt hatten, waren zu Beginn des 19. Jahrhunderts weitgehend aufgelöst. Städtische und private Initiativen traten an ihre Stelle. In Koblenz machte sich vor allem die "katholische Junta", wie der Kreis um Dietz von seinen Gegnern genannt wurde, um die Armen verdient. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 67.)

Nach jahrelangen zähen Verhandlungen gab das Kriegsministerium im März 1890 die gesamte Stadtbefestigung von Koblenz und Ehrenbreitstein und den Hauptabschnitt der Feste Franz auf. Damit wurde das ganze in der Rhein- und Moselebene gelegene Stadtgebiet von allen Baubeschränkungen befreit. Für die Stadt begann in politischer, sozialer und wirtschaftlicher Hinsicht ein neuer historischer Abschnitt. Die Bautätigkeit, die vor allem südlich der alten Stadt nach 1890 rasch einsetzte, veränderte das Erscheinungsbild von Koblenz grundlegend. 
Der Kölner Städteplaner Joseph Stübben (1845–1936) legte bereits im Januar 1889 einen Plan zur Erweiterung der Stadt nach Süden und nach Westen vor. Entsprechend anderer Stadtplanungen der Gründerzeit sah Stübben einerseits breite, gerade Straßen mit Pracht- und Alleencharakter vor, die in Verkehrsplätzen mit Fächer-, Stern-, oder Rechteckform münden sollten. Andererseits sollten monumentale Gebäude, ein neuer Hauptbahnhof und mehrere Kirchen, die die neuen Stadtteile gliedern und "Fernblicke" ermöglichen. Diese Planungen wurden nicht in vollem Umfang realisiert. Aber es war unübersehbar, dass die Koblenzer Stadterweiterung das gestärkte Selbstbewusstsein der wilhelminischen Gesellschaft zum Ausdruck brachte. Die eingeebneten Wälle und Festungswerke wurden in Anlagen und Ringstraßen verwandelt, die mit Monumentalbauten und architektonisch wirksamen Wohnhäusern besetzt wurden. In beeindruckenden Dimensionen waren mit einer Breite von 52 Metern der Kaiser-Wilhelm-Ring (heute: Friedrich-Ebert-Ring), aber auch der 1902 fertiggestellte neue Hauptbahnhof und die strenge neugotische St.-Josefs-Kirche mit ihrem enormen Nordturm ausgelegt. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 102.)

Der größte neue Stadtteil, die Südliche Vorstadt, befriedigte bezeichnenderweise einerseits die Nachfrage der Oberschicht nacht repräsentatioven Villen und andererseits die Wohnraumbedürfnisse des "bessergestellten Mittelstandes", wie es in einem städtischen Verwaltungsbericht für die Jahre 1902/1903 hieß. Gesunde und preiswerte Arbeiterwohnungen entstanden demgegenüber kaum. Die Wohnverhältnisse in der Altstadt verschlechterten sich vielmehr. Nach "angestellten Ermittlungen" bestätigte die Stadtverwaltung im Juli 1901, "dass trotz der starken Bautätigkeit der letzten Jahre, welche in den Vorstadtbezirken gesunde und schöne Wohnungen für den Mittelstand geschaffen" hatte, "für Arbeiter und kleine Beamte [...] wenigen geschehen" war. Diese waren vielmehr "nach wie vor auf die eng bevölkerten Bezirke der Altstadt angewiesen." (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 105.)

Der enorme Bevölkerungszuwachs im späten 19. Jahrhundert stellte auch Koblenz vor die Notwendigkeit, eine Fülle neuer Aufgaben zu übernehmen. Zu den wichtigsten zählte die hygienische Vorsorge. Nachdem sich die Wasserqualität der innerstädtischen Brunnen zusehends verschlechtert hatte, baute man 1888 ein leistungsfähiges Wasserwerk. Auch der Verkehr wuchs und die Verkehrsbedingungen wurden moderner. Eine Koblenzer Straßenbahngesellschaft wurde 1884 als Privatunternehmen gegründet, das 1887 zwei Pferdebahnen auf einer Ost-West- und Nord-Süd-Linie betrieb. 1898/1900 ging das Unternehmen – im Gegensatz zur zögerlichen Stadtverwaltung – zum elektrischen Betrieb über und baute ihr gesamtes Liniennetz aus. Die Stadt wurde unübersehbar städtischer, kommerzieller, weniger traditionell, mobiler und dynamischer. Aber die soziale Reformbereitschaft auf kommunaler Ebene ging mit einer erheblichen politischen Illiberalität einher. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 108-109.)

### Das Kaiser-Wilhelm-Denkmal

Mehrfach hatte der Stadtrat bekräftigt, dass die Stadt Koblenz der richtige Standort für ein Kaiser-Wilhelm-Denkmal im Rheinland und für alle Rheinländer sei. Nach langwierigen Auseinandersetzungen über die Standortfrage, die Wilhelm II. im Sinne von Koblenz beendete, konnte das Denkmal im Jahre 1897 fertiggestellt werden.Insgesamt hatten die Diskussionen damit neun Jahre angedauert. 
Auf die Ausführung des Denkmals hatten die Initiatoren, das Koblener Komitee und der Stadtrat, nur wenig Einfluss. Die architektonische Gestaltung des Denkmals entschied im wesentlichen Wilhelm II. Dabei war das Koblenzer Denkmal keineswegs das einzige seiner Art. In den Jahren 1896 und 1897 wurden allein vier weitere monumentale Kaiser-Wilhelm-Denkmäler in Preußen eingeweiht. Grund für die Denkmalwelle war nicht die sentimentale Rückbesinnung auf einen alten Herrscher, sondern Machtdemonstration und die Idealisierung von Monarchie und Kaiserwürde waren die treibenden Motive. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 117.)

## Der Erste Weltkrieg

Die verkehrsgeographisch günstige Lage mit Brücken und Eisenbahnverbindungen in alle vier Himmelsrichtungen machte Koblenz zu einem wichtigen Etappenort für den deutschen Aufmarsch an der Westfront. In Schulen, Gasthäusern und öffentlichen Gebäuden mussten Quartiere für die einberufenen Reservisten bereitgestellt werden. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 119.)

Der Krieg erfasste sehr schnell alle Lebensbereiche der Bevölkerung. Nachts mussten die Straßenlaternen gelöscht, vorübergehend auch die Häuser verdunkelt werden. In den Kirchen fanden Kriegstrauungen statt, und die Höheren Schulen entließen mit „Notreifeprüfungen“ ihre Abiturienten als Kriegsfreiwillige in den „Kampf für das Vaterland“. Die Frauenvereine baten um Meldungen für den Pflegedienst bei Verwundeten, und sachverständige Männer und Frauen nahmen ehrenamtlich ihre Tätigkeit in Bürgerausschüssen auf, die in Zusammenarbeit mit den von der Stadtverwaltung sehr bald eingerichteten Kartoffel-, Garten-, Obst- und Milchämtern, der Kohlenverteilungs- und Bekleidungsstellen die Versorgung der Bevölkerung mit Lebensmitteln und Verbrauchsgütern besorgen sollten. (Quelle: Geschichte der Stadt Koblenz, Stuttgart 1993, S. 121.)